apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: cloudevent
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: NatssChannel
    name: cloudevent
  subscriber:
    uri: http://hello-display.cloudevent.svc.cluster.local