apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receive-hello
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: asia.gcr.io/pinjyun/receive-hello:latest
      imagePullSecrets:
      - name: gcr-json-key