apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: receive-hello
build:
  artifacts:
  - image: asia.gcr.io/pinjyun/receive-hello
    context: ./
  googleCloudBuild:
    projectId: pinjyun
    kanikoImage: gcr.io/kaniko-project/executor:v1.3.0
deploy:
  kustomize:
    paths:
    - kustomize
