apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: graphql-server
build:
  artifacts:
  - image: asia.gcr.io/pinjyun/graphql-server
    context: src
  googleCloudBuild:
    projectId: pinjyun
    kanikoImage: gcr.io/kaniko-project/executor:v1.3.0
deploy:
  kustomize:
    paths:
    - kustomize
