apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: send-hello
build:
  artifacts:
  - image: asia.gcr.io/pinjyun/send-hello
    context: ./
    kaniko: {}
  googleCloudBuild:
    projectId: pinjyun
deploy:
  kustomize:
    paths:
    - kustomize
