apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graphql-server
spec:
  template:
    spec:
      containers:
      - image: asia.gcr.io/pinjyun/graphql-server
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /app/config.yaml
          subPath: config.yaml
          name: config
      imagePullSecrets:
      - name: gcr-json-key
      volumes:
      - name: config
        configMap:
          name: config.yaml
          items:
          - key: config.yaml
            path: config.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config.yaml
data:
  config.yaml: |
    port: 3000
    mysql:
      host: mysql.graphql.svc.cluster.local
      user: root
      password: root
      database: classicmodels